name: Dependency-Check

on: push

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Dependency-Check
      uses: guilhermemarimzup/dependency-vuln-checker@development
